INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('10','กรุงเทพมหานคร','Bangkok');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('11','สมุทรปราการ','Samut Prakarn');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('12','นนทบุรี','Nonthaburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('13','ปทุมธานี','Pathum Thani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('14','พระนครศรีอยุธยา','Phra Nakhon Si Ayutthaya');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('15','อ่างทอง','Ang Thong');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('16','ลพบุรี','Lop Buri');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('17','สิงห์บุรี','Sing Buri');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('18','ชัยนาท','Chai Nat');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('19','สระบุรี','Saraburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('20','ชลบุรี','Chon Buri');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('21','ระยอง','Rayong');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('22','จันทบุรี','Chanthaburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('23','ตราด','Trat');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('24','ฉะเชิงเทรา','Chachoengsao');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('25','ปราจีนบุรี','Prachin Buri');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('26','นครนายก','Nakhon Nayok');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('27','สระแก้ว','Sa kaeo');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('30','นครราชสีมา','Nakhon Ratchasima');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('31','บุรีรัมย์','Buri Ram');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('32','สุรินทร์','Surin');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('33','ศรีสะเกษ','Si Sa Ket');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('34','อุบลราชธานี','Ubon Ratchathani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('35','ยโสธร','Yasothon');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('36','ชัยภูมิ','Chaiyaphum');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('37','อำนาจเจริญ','Amnat Charoen');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('38','บึงกาฬ','Bueng Kan');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('39','หนองบัวลำภู','Nong Bua Lam Phu');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('40','ขอนแก่น','Khon Kaen');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('41','อุดรธานี','Udon Thani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('42','เลย','Loei');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('43','หนองคาย','Nong Khai');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('44','มหาสารคาม','Maha Sarakham');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('45','ร้อยเอ็ด','Roi Et');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('46','กาฬสินธุ์','Kalasin');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('47','สกลนคร','Sakon Nakhon');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('48','นครพนม','Nakhon Phanom');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('49','มุกดาหาร','Mukdahan');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('50','เชียงใหม่','Chiang Mai');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('51','ลำพูน','Lamphun');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('52','ลำปาง','Lampang');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('53','อุตรดิตถ์','Uttaradit');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('54','แพร่','Phrae');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('55','น่าน','Nan');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('56','พะเยา','Phayao');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('57','เชียงราย','Chiang Rai');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('58','แม่ฮ่องสอน','Mae Hong Son');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('60','นครสวรรค์','Nakhon Sawan');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('61','อุทัยธานี','Uthai Thani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('62','กำแพงเพชร','Kamphaeng Phet');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('63','ตาก','Tak');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('64','สุโขทัย','Sukhothai');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('65','พิษณุโลก','Phitsanulok');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('66','พิจิตร','Phichit');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('67','เพชรบูรณ์','Phetchabun');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('70','ราชบุรี','Ratchaburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('71','กาญจนบุรี','Kanchanaburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('72','สุพรรณบุรี','Suphan Buri');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('73','นครปฐม','Nakhon Pathom');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('74','สมุทรสาคร','Samut Sakhon');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('75','สมุทรสงคราม','Samut Songkhram');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('76','เพชรบุรี','Phetchaburi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('77','ประจวบคีรีขันธ์','Prachuap Khiri Khan');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('80','นครศรีธรรมราช','Nakhon Si Thammarat');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('81','กระบี่','Krabi');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('82','พังงา','Phang-nga');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('83','ภูเก็ต','Phuket');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('84','สุราษฎร์ธานี','Surat Thani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('85','ระนอง','Ranong');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('86','ชุมพร','Chumphon');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('90','สงขลา','Songkhla');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('91','สตูล','Satun');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('92','ตรัง','Trang');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('93','พัทลุง','Phatthalung');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('94','ปัตตานี','Pattani');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('95','ยะลา','Yala');
INSERT INTO mas_province (province_id, province_tname, province_ename) VALUES ('96','นราธิวาส','Narathiwat');
